const constants = Object.freeze({
    UNASSIGNED: 0,
    BOARD_SIZE: 9,
    NUM_GUESSES: 9,
    BLOCK_SIZE: 3,
    EASY_DIFFICULTY: 0.8,
    MEDIUM_DIFFICULTY: 0.6,
    HARD_DIFFICULTY: 0.4,
    EXPERT_DIFFICULTY: 0.2
});

const {
    UNASSIGNED,
    BOARD_SIZE,
    NUM_GUESSES,
    BLOCK_SIZE,
    EASY_DIFFICULTY,
    MEDIUM_DIFFICULTY,
    HARD_DIFFICULTY,
    EXPERT_DIFFICULTY
} = constants;

export {
    UNASSIGNED,
    BOARD_SIZE,
    NUM_GUESSES,
    BLOCK_SIZE,
    EASY_DIFFICULTY,
    MEDIUM_DIFFICULTY,
    HARD_DIFFICULTY,
    EXPERT_DIFFICULTY
};
